[build.environment]
  NPM_FLAGS = "--version"
  
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/static/admin"
  status = 200
