backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'docs'
    label: 'Docs'
    label_singular: 'Doc'
    folder: 'docs'
    path: '{{menu}}/{{id}}'
    create: true
    slug: '{{id}}'
    identifier_field: 'title'
    extension: 'md'
    format: 'frontmatter'
    editor:
      preview: false
    fields:
      # - name: 'menu'
      #   label: 'Menu'
      - { label: 'Slug', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hide Title', name: 'hide_title', widget: 'boolean', default: false }
      - { label: 'Hide Table of Contents', name: 'hide_table_of_contents', widget: 'boolean', default: false }
      - { label: 'Sidebar Label', name: 'sidebar_label', widget: 'string', required: false }
      - { label: 'Keywords', name: 'keywords', widget: 'list', default: [], required: false }
      - { label: 'Description', name: 'description', required: false }
      - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  
